import React, { useEffect, useMemo, useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { Country } from 'country-state-city';
import Modal from '../ui/Modal';
import Spinner from '../ui/Spinner';
import { Button } from '../ui/primitives/button';
import { PlayerAvatar } from '../players/PlayerAvatar';
import { useUploadFile } from '../../api/hooks';
import { useToast } from '../../hooks/useToast';
import {
  EMPTY_STATISTICIAN_FORM,
  fromStatistician,
  generatePassword,
  toCreatePayload,
  toUpdatePayload,
  statisticianFormSchema,
  type StatisticianFormValues,
} from './statistician-form';
import type { Statistician, StatisticianCreateBody, StatisticianUpdateBody } from '../../types/api';

const inputClass =
  'w-full rounded-md border border-gray-300 bg-white px-3 py-2 text-sm text-gray-900 focus:outline-none focus:ring-2 focus:ring-court-400 aria-[invalid=true]:border-rose-500 disabled:opacity-60 dark:border-gray-700 dark:bg-gray-900 dark:text-white';

function Field({ id, label, error, required, hint, children, className }: { id: string; label: string; error?: string; required?: boolean; hint?: string; children: React.ReactNode; className?: string }) {
  return (
    <div className={`flex flex-col gap-1.5 ${className ?? ''}`}>
      <label htmlFor={id} className="text-sm font-medium text-gray-700 dark:text-gray-300">
        {label}
        {required && <span aria-hidden className="text-rose-600"> *</span>}
      </label>
      {children}
      {hint && !error && <p className="text-xs text-gray-500">{hint}</p>}
      {error && <p id={`${id}-error`} className="text-xs text-rose-600">{error}</p>}
    </div>
  );
}

/**
 * Create or edit a statistician. A create goes to `POST /statistician` with a password the admin sets
 * (generated by default, with a copy button, because the backend would otherwise fall back to a fixed
 * default); an edit goes to `PATCH /statistician/:id` and sends only what changed.
 *
 * The photo is uploaded as soon as it's picked and sent as a URL with the rest of the body, so it is
 * one save, not a save followed by a second request that can fail on its own.
 */
const StatisticianFormDialog: React.FC<{
  open: boolean;
  onClose: () => void;
  initial?: Statistician | null;
  isSaving: boolean;
  serverError?: string | null;
  onCreate: (body: StatisticianCreateBody) => void;
  onUpdate: (body: StatisticianUpdateBody) => void;
}> = ({ open, onClose, initial, isSaving, serverError, onCreate, onUpdate }) => {
  const editing = !!initial;
  const uploadFile = useUploadFile();
  const toast = useToast();
  const countries = useMemo(() => Country.getAllCountries().map((c) => c.name).sort((a, b) => a.localeCompare(b)), []);

  const baseline = useMemo(() => (initial ? fromStatistician(initial) : EMPTY_STATISTICIAN_FORM), [initial]);
  const schema = useMemo(() => statisticianFormSchema(baseline, editing), [baseline, editing]);
  const {
    register,
    handleSubmit,
    reset,
    setValue,
    getValues,
    watch,
    formState: { errors, isDirty },
  } = useForm<StatisticianFormValues>({ defaultValues: baseline, resolver: zodResolver(schema) });
  const [confirmingDiscard, setConfirmingDiscard] = useState(false);
  const [showPassword, setShowPassword] = useState(false);
  const [copied, setCopied] = useState(false);

  // Start fresh whenever the dialog opens, for a different statistician or a new one. A new account
  // starts with a generated password so there is always something to copy.
  useEffect(() => {
    if (!open) return;
    reset(initial ? baseline : { ...baseline, password: generatePassword() });
    setConfirmingDiscard(false);
    setShowPassword(!initial);
    setCopied(false);
    // reset only when the dialog opens or switches person; baseline follows `initial`
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open, initial?.id]);

  const [firstName, lastName, photo, password] = watch(['firstName', 'lastName', 'photo', 'password']);
  const busy = isSaving || uploadFile.isPending;

  const requestClose = () => {
    if (busy) return;
    if (isDirty) setConfirmingDiscard(true);
    else onClose();
  };

  const pickPhoto = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    e.target.value = '';
    if (!file) return;
    uploadFile.mutate(file, {
      onSuccess: (res) => setValue('photo', res.url, { shouldDirty: true }),
      onError: (err) => toast.error(`Couldn’t upload the photo: ${err.message}`),
    });
  };

  const copyPassword = async () => {
    try {
      await navigator.clipboard.writeText(getValues('password'));
      setCopied(true);
    } catch {
      setCopied(false);
      toast.error('Couldn’t copy. Select the password and copy it by hand.');
    }
  };

  const regenerate = () => {
    setValue('password', generatePassword(), { shouldDirty: true });
    setCopied(false);
    setShowPassword(true);
  };

  const submit = handleSubmit((values) => {
    if (editing) onUpdate(toUpdatePayload(values, baseline));
    else onCreate(toCreatePayload(values));
  });

  const invalid = (k: keyof StatisticianFormValues) => (errors[k] ? true : undefined);
  const describedBy = (k: keyof StatisticianFormValues) => (errors[k] ? `${k}-error` : undefined);
  const msg = (k: keyof StatisticianFormValues) => errors[k]?.message;

  return (
    <Modal open={open} onClose={requestClose} title={editing ? 'Edit statistician' : 'Add statistician'} size="lg" closeOnBackdropClick={!busy} closeOnEscape={!busy}>
      <form onSubmit={submit} className="flex flex-col gap-6" noValidate aria-busy={busy}>
        {serverError && (
          <p role="alert" className="rounded-md border border-rose-200 bg-rose-50 px-3 py-2 text-sm text-rose-700 dark:border-rose-500/30 dark:bg-rose-500/10 dark:text-rose-300">
            {serverError}
          </p>
        )}

        <div className="flex items-center gap-4">
          <PlayerAvatar
            firstName={firstName}
            lastName={lastName}
            photo={photo}
            size="lg"
            className={uploadFile.isPending ? 'opacity-50' : undefined}
          />
          <div className="flex flex-col gap-1">
            <label className="inline-flex w-fit items-center gap-2 rounded-md border border-gray-300 px-3 py-1.5 text-sm font-semibold text-gray-700 hover:bg-gray-50 dark:border-gray-700 dark:text-gray-200 dark:hover:bg-gray-800">
              {uploadFile.isPending && <Spinner className="size-3.5" />}
              {uploadFile.isPending ? 'Uploading…' : photo ? 'Replace photo' : 'Upload photo'}
              <input type="file" accept="image/*" className="sr-only" onChange={pickPhoto} disabled={busy} />
            </label>
            <span className="text-xs text-gray-500">Without one, their initials are shown.</span>
          </div>
        </div>

        <fieldset className="grid gap-4 md:grid-cols-2" disabled={busy}>
          <legend className="sr-only">Statistician details</legend>
          <Field id="firstName" label="First name" required error={msg('firstName')}>
            <input id="firstName" className={inputClass} {...register('firstName')} aria-invalid={invalid('firstName')} aria-describedby={describedBy('firstName')} autoFocus />
          </Field>
          <Field id="lastName" label="Last name" required error={msg('lastName')}>
            <input id="lastName" className={inputClass} {...register('lastName')} aria-invalid={invalid('lastName')} aria-describedby={describedBy('lastName')} />
          </Field>
          <Field id="email" label="Email" required={!editing} error={msg('email')} hint={editing ? 'The email is their sign-in, so it can’t be changed here.' : undefined} className="md:col-span-2">
            <input id="email" type="email" {...register('email')} aria-invalid={invalid('email')} aria-describedby={describedBy('email')} readOnly={editing} className={`${inputClass} ${editing ? 'bg-gray-50 text-gray-500 dark:bg-gray-800' : ''}`} />
          </Field>
        </fieldset>

        <fieldset className="grid gap-4 md:grid-cols-2" disabled={busy}>
          <legend className="mb-2 text-sm font-semibold text-gray-900 dark:text-white">Contact</legend>
          <Field id="phone" label="Phone" error={msg('phone')}>
            <input id="phone" className={inputClass} {...register('phone')} aria-invalid={invalid('phone')} aria-describedby={describedBy('phone')} />
          </Field>
          <Field id="country" label="Country" error={msg('country')}>
            <input id="country" className={inputClass} {...register('country')} list="statistician-countries" autoComplete="off" aria-invalid={invalid('country')} aria-describedby={describedBy('country')} />
            <datalist id="statistician-countries">
              {countries.map((c) => <option key={c} value={c} />)}
            </datalist>
          </Field>
          <Field id="state" label="State" error={msg('state')}>
            <input id="state" className={inputClass} {...register('state')} aria-invalid={invalid('state')} aria-describedby={describedBy('state')} />
          </Field>
          <Field id="homeAddress" label="Home address" error={msg('homeAddress')}>
            <input id="homeAddress" className={inputClass} {...register('homeAddress')} aria-invalid={invalid('homeAddress')} aria-describedby={describedBy('homeAddress')} />
          </Field>
        </fieldset>

        <fieldset className="flex flex-col gap-3" disabled={busy}>
          <legend className="mb-2 text-sm font-semibold text-gray-900 dark:text-white">
            {editing ? 'Reset password (optional)' : 'Password'}
          </legend>
          <Field
            id="password"
            label={editing ? 'New password' : 'Password'}
            required={!editing}
            error={msg('password')}
            hint={editing ? 'Leave blank to keep their current password.' : 'Share this with them yourself. It isn’t emailed, and you can’t see it again after saving.'}
          >
            <div className="flex flex-wrap gap-2">
              <input
                id="password"
                type={showPassword ? 'text' : 'password'}
                className={`${inputClass} min-w-0 flex-1 font-mono`}
                {...register('password', { onChange: () => setCopied(false) })}
                aria-invalid={invalid('password')}
                aria-describedby={describedBy('password')}
                autoComplete="new-password"
              />
              <Button type="button" variant="secondary" onClick={() => setShowPassword((s) => !s)}>{showPassword ? 'Hide' : 'Show'}</Button>
              <Button type="button" variant="secondary" onClick={regenerate}>Generate</Button>
              <Button type="button" variant="secondary" onClick={() => void copyPassword()} disabled={!password}>{copied ? 'Copied' : 'Copy'}</Button>
            </div>
          </Field>
        </fieldset>

        {editing && (
          <fieldset disabled={busy}>
            <Field id="status" label="Status" hint="An inactive statistician can’t sign in or be assigned to matches.">
              <select id="status" className={inputClass} {...register('status')}>
                <option value="ACTIVE">Active</option>
                <option value="INACTIVE">Inactive</option>
              </select>
            </Field>
          </fieldset>
        )}

        <div className="flex flex-wrap items-center justify-end gap-3 border-t border-gray-200 pt-4 dark:border-gray-800">
          {confirmingDiscard ? (
            <div role="alertdialog" aria-label="Discard unsaved changes" className="mr-auto flex flex-wrap items-center gap-3 text-sm">
              <span className="text-gray-700 dark:text-gray-300">Discard your unsaved changes?</span>
              <Button variant="secondary" type="button" onClick={() => setConfirmingDiscard(false)}>Keep editing</Button>
              <Button variant="destructive" type="button" onClick={onClose}>Discard</Button>
            </div>
          ) : (
            <Button variant="secondary" type="button" onClick={requestClose} disabled={busy}>Cancel</Button>
          )}
          <Button type="submit" disabled={busy || confirmingDiscard} className="min-w-28">
            {isSaving && <Spinner />}
            {isSaving ? 'Saving…' : editing ? 'Save changes' : 'Add statistician'}
          </Button>
        </div>
      </form>
    </Modal>
  );
};

export default StatisticianFormDialog;
